"""Fix schemas

Revision ID: c2eba45dc509
Revises: 60f7bd631a27
Create Date: 2024-11-03 01:10:42.214795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2eba45dc509'
down_revision: Union[str, None] = '60f7bd631a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.add_column('user', sa.Column('registered_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('user', 'registered_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('user', 'registered_at')
    op.alter_column('operation', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
